"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { getAddress, parseEventLogs, type Address } from "viem";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Card } from "@/components/ui/card";
import { PrivacyLabel } from "@/components/ui/privacy-label";
import { InlineError } from "@/components/web3/inline-error";
import { NetworkGuard } from "@/components/web3/network-guard";
import { TransactionStatus, type TransactionState } from "@/components/web3/transaction-status";
import { WalletGuard } from "@/components/web3/wallet-guard";
import { createFairCirclePublicClient, createFairCircleWalletClient } from "@/lib/web3/clients";
import { withTransientRpcRetry } from "@/lib/web3/retry";
import { useWallet } from "@/lib/web3/use-wallet";
import { coordinatorAbi, coordinatorAddress, fairCircleAbi, fairCircleAddress, parsePlanCreatedReceipt, safePlanError, SplitMethod } from "./contract";

export function PlanTogetherCreateForm() { const wallet = useWallet(); const router = useRouter(); const busy = useRef(false); const [title, setTitle] = useState(""); const [members, setMembers] = useState(["", ""]); const [options, setOptions] = useState(["", ""]); const [deadline, setDeadline] = useState(""); const [method, setMethod] = useState<number>(SplitMethod.Equal); const [recipient, setRecipient] = useState(""); const [collectionDeadline, setCollectionDeadline] = useState(""); const [state, setState] = useState<TransactionState>("idle"); const [hash, setHash] = useState<string>(); const [error, setError] = useState<string>();
  async function submit() { if (busy.current) return; busy.current = true; setError(undefined); const clean = members.map((v) => v.trim()); const costs = options.filter(Boolean).map((v) => BigInt(v)); if (!wallet.provider || !wallet.address || !wallet.isSepolia || !title.trim() || clean.length < 2 || clean.some((v) => !/^0x[a-fA-F0-9]{40}$/.test(v)) || new Set(clean.map((v) => v.toLowerCase())).size !== clean.length || costs.length < 1 || costs.some((v) => v <= 0n) || !/^0x[a-fA-F0-9]{40}$/.test(recipient) || new Date(deadline).getTime() <= Date.now() || new Date(collectionDeadline).getTime() <= Date.now()) { setState("failed"); setError("Complete the form with unique addresses, positive costs, and future deadlines."); busy.current = false; return; }
    try { setState("preparing"); const p = createFairCirclePublicClient(); const w = createFairCircleWalletClient(wallet.provider, wallet.address); const budget = await withTransientRpcRetry(() => p.simulateContract({ address: fairCircleAddress, abi: fairCircleAbi, functionName: "createQuietBudgetRoom", args: [title.trim(), clean as Address[], costs, BigInt(Math.floor(new Date(deadline).getTime() / 1000)), 3], account: wallet.address })); setState("awaiting-wallet"); const budgetHash = await w.writeContract(budget.request); setHash(budgetHash); setState("confirming"); const budgetReceipt = await withTransientRpcRetry(() => p.waitForTransactionReceipt({ hash: budgetHash })); const logs = parseEventLogs({ abi: fairCircleAbi, eventName: "RoomCreated", logs: budgetReceipt.logs.filter((log) => getAddress(log.address) === fairCircleAddress), strict: true }); if (logs.length !== 1 || Number((logs[0].args as any).mode) !== 3) throw new Error("The confirmed budget room was not a Plan Together room."); const budgetRoomId = BigInt((logs[0].args as any).roomId); const plan = await withTransientRpcRetry(() => p.simulateContract({ address: coordinatorAddress, abi: coordinatorAbi, functionName: "createPlanFromBudgetRoom", args: [budgetRoomId, method, recipient.trim() as Address], account: wallet.address })); setState("awaiting-wallet"); const planHash = await w.writeContract(plan.request); setHash(planHash); setState("confirming"); const receipt = await withTransientRpcRetry(() => p.waitForTransactionReceipt({ hash: planHash })); if (receipt.status !== "success") throw new Error("The confirmed plan transaction was reverted."); const created = parsePlanCreatedReceipt(receipt, wallet.address); setState("confirmed"); router.push(`/plan-together/${created.planId}`); } catch (cause) { setState("failed"); setError(safePlanError(cause)); } finally { busy.current = false; } }
  return <AppShell><div className="space-y-8"><PageHeader eyebrow="Plan Together" title="Create a guided plan" description="Start with a private budget decision, then progress through a split and confidential collection." /><WalletGuard><NetworkGuard><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Card><form className="space-y-5" onSubmit={(e) => { e.preventDefault(); void submit(); }}><Field label="Plan title"><input className={inputClass} value={title} maxLength={80} onChange={(e) => setTitle(e.target.value)} /></Field><div><p className="text-sm font-semibold">Group members</p>{members.map((v, i) => <input key={i} aria-label={`Member ${i + 1}`} className={inputClass} value={v} onChange={(e) => setMembers(members.map((x, n) => n === i ? e.target.value : x))} />)}<button type="button" className={linkClass} onClick={() => setMembers([...members, ""])}>Add member</button></div><div><p className="text-sm font-semibold">Budget options</p>{options.map((v, i) => <input key={i} aria-label={`Option ${i + 1}`} className={inputClass} inputMode="numeric" value={v} onChange={(e) => setOptions(options.map((x, n) => n === i ? e.target.value : x))} />)}<button type="button" className={linkClass} onClick={() => setOptions([...options, ""])}>Add option</button></div><Field label="Budget deadline"><input className={inputClass} type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></Field><Field label="Split method"><select className={inputClass} value={method} onChange={(e) => setMethod(Number(e.target.value))}><option value={SplitMethod.Equal}>Equal</option><option value={SplitMethod.CapacityWeighted}>Capacity weighted</option></select></Field><Field label="Collection recipient"><input className={inputClass} value={recipient} onChange={(e) => setRecipient(e.target.value)} /></Field><Field label="Collection deadline"><input className={inputClass} type="datetime-local" value={collectionDeadline} onChange={(e) => setCollectionDeadline(e.target.value)} /></Field><button className={buttonClass} type="submit" disabled={state === "preparing" || state === "awaiting-wallet" || state === "confirming"}>Create plan</button>{error ? <InlineError message={error} /> : null}</form></Card><aside className="space-y-4"><TransactionStatus state={state} hash={hash} error={error} /><PrivacyLabel>Capacities, shares and contributions are encrypted. Public room configuration and group addresses remain visible.</PrivacyLabel></aside></div></NetworkGuard></WalletGuard></div></AppShell>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold">{label}{children}</label>; }
const inputClass = "mt-2 w-full rounded-md border border-slate-300 px-3 py-2 text-sm"; const buttonClass = "rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"; const linkClass = "mt-2 text-sm font-semibold text-teal-800 underline";
